Adds ERP
Whitesands13/Whitesands pull request #275
Opened 2020-06-11 04:34 UTC by TheNeoGamer42

## About The Pull Request
adds a perfectly normal emote, *sex
## Why It's Good For The Game
sex good
## Changelog
:cl:
add: an ERP emote, *sex
/:cl:

2020-06-11 04:35 UTC, Superyodeler commented
It's even modularized properly

2020-06-11 04:35 UTC, dinnerwoerror commented on waspstation/code/modules/mob/emote.dm
> +		user.gib()
if(.)
user.gib()

2020-06-11 04:36 UTC, TheNeoGamer42 commented
I take pride in adding the best feature to the game, why wouldn't I modularize it?

2020-06-11 04:36 UTC, TheNeoGamer42 commented on waspstation/code/modules/mob/emote.dm
> +		user.gib()
I believe that is how one has sex, right?

2020-06-11 04:45 UTC, TheNeoGamer42 commented
There is now an appropriate sound for *sex

2021-05-25 02:02 UTC, TheNeoGamer42 commented
I wonder if this even works still

2021-05-25 02:03 UTC, Shadowtail117 requested changes
The modularization folder is no longer `waspstation`, it's `whitesands`.

2021-05-25 02:03 UTC, TheNeoGamer42 commented
true, idfk how to change it without reinstalling it and shit though

2021-05-25 02:04 UTC, Shadowtail117 commented
Given your last commit was June 10th of last year, the branch is likely way too outdated to reasonably salvage. I recommend starting with a new branch that's been fast-forwarded and carrying your changes over to there in a new PR.

2021-05-25 19:09 UTC, TheRealScarHomie commented
remember to tactically sex in near death situations, your brain can be salvaged easier than your body

2021-06-15 13:53 UTC, closed without merging