Ntos management thingies
Whitesands13/Whitesands pull request #660
Opened 2020-12-24 01:02 UTC by MarkSuckerberg

## About The Pull Request
Adds management and creation of bank accounts through two new NTOS apps. One manages staff in your department's paychecks, the other allows for the creation, monitoring, and removal of bank accounts.

## Why It's Good For The Game
Bank accounts have long been an intangible and untouchable concept. This aims to remedy this by allowing department heads to give you pay raises and cuts, as well as giving the Captain, HoP, and QM (to a lesser degree, the QM can only create accounts, no removals or adjustments) the ability to add new accounts to wayward ashwalkers and charlie station scientists.  

## Changelog
:cl:
add: NTOS App for the management of all bank accounts
add: NTOS App for the management of departmental paychecks and termination
tweak: Allows the freezing/unfreezing of accounts and budgets from the appropriate management app
/:cl:

2020-12-24 01:54 UTC, Maldaris commented on code/modules/economy/account.dm
> +		bank_card_talk("ERROR: Payday aborted, account frozen!")
there's no return method/break here. Does this actually abort the payout?

2020-12-24 01:54 UTC, Maldaris commented on code/modules/economy/account.dm
>  		if(D)
Same here, presumably needs an elseif?

2020-12-24 06:46 UTC, MarkSuckerberg commented on code/modules/economy/account.dm
> +		bank_card_talk("ERROR: Payday aborted, account frozen!")
this explains a lot

2021-02-11 17:06 UTC, Superyodeler requested changes
Deleting an account doesn't work and there needs to be a message for attempting to withdraw funds from a frozen card. It's also possible to put two entries on the same account number, but I'm not sure that's a problem.

2021-02-11 17:06 UTC, Superyodeler commented on code/modules/economy/account.dm
> +	var/frozen = FALSE
When attempting to withdraw money from a frozen card I get the message "ERROR: The linked account requires -5022.22 more credits to perform that withdrawal." We need a message to make it clear what's actually happening.

2021-02-19 06:18 UTC, Superyodeler approved these changes
Looks good!

2021-02-20 04:11 UTC, triplezeta commented
Account creation works like a charm. Goes for the entire bank account creation app; it just works. Setting paycheck amounts is easy, creating new accounts is also easy.

The departmental account manager app is less reliable. Account deletion does not seem to work properly. Changing the paycheck using the departmental account manager causes it to null. Freezing budget cards works properly, preventing transactions in and out of it, but it also will cause it to eat any holochips put in.

2021-02-20 04:16 UTC, Superyodeler commented
I think the departmental manager doesn't allow you to delete accounts, just demote to assistant

2021-02-23 05:15 UTC, merged