An Update to the Space Russian Arsenal: The AK-47
Whitesands13/Whitesands pull request #748
Opened 2021-02-06 04:23 UTC by coleminerman

## About The Pull Request

This PR adds a new weapon to the game, the AK-47. If the Space Russians exist, why shouldn't their most iconic weapon? Also adds the weapon to the Russian Surplus cargo crate, as it felt like it was lacking something like this. The AK comes with a custom sprite based on that of the AKS-74U but highly modified by me, and, of course, ammunition for the weapon.

## Why It's Good For The Game

The Russian Surplus crate has always felt to me like it was missing something. It included the Mosin-Nagant and a Russian uniform appropriate for the time period in which the Nagant was used, but it also included more modern Russian military gear, and didn't include a weapon that goes with that. As such, this PR aims to fix that problem. It adds an iconic Russian weapon, the AK-47, to go along with the modern Russian gear both aesthetically and functionally. While this does certainly buff Gun Cargo's capabilities, this was balanced by increasing the cost of the Russian Surplus crates by 3000 credits (an amount suggested by other coders). This also adds the ammo type used by the AK-47 to the Russian Surplus crates, as well as to the Ammo Surplus crates, both of which are obtainable by Cargo.

## Changelog
:cl:
add: Added the AK-47 automatic rifle as well as its ammo, both of which can only be obtained through cargo purchases (the ammo can also be found in one of the ruins on White Sands, though it is found alongside a different gun that uses the same type and existed before this PR).
balance: Changed the price of the Russian Surplus crate accordingly in order to balance the weapon. Also changed the damage amount done by the ammo type, as it was a bit too high (killed in only 7 shots with an automatic weapon).
imageadd: Added a new sprite for the AK-47.
code: Coded the AK-47 and its ammo.
/:cl:

2021-02-06 04:28 UTC, triplezeta approved these changes
the 48x32 gun revolution is here.

2021-02-06 04:30 UTC, Maldaris requested changes
This looks good but there's a few nitpicks here.

2021-02-06 04:30 UTC, Maldaris commented on whitesands/code/modules/projectiles/boxes_magazines/external/rifle.dm
> +	caliber = "5.45x39mm"
The OG AK-47 is chambered in 7.62x39mm FMJ.

You'll want to make a separate ammo type for this one.

2021-02-06 04:30 UTC, Maldaris commented on whitesands/code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = {"A favorite among both the soldiers of the Space Russain Army and civillians out on the edges of explored space, the AK-47 is a reliable rifle designed and sold by a Space Russian company an
Might spellcheck this a little closer, I think you spelled civilians wrong.

Also "Space Russian Army" sounds 10/10 cheesy, "Russian Colonial Army" or something similar would be better imo, but I could go either way. Bonus points if you can find precedents in code.

2021-02-06 04:30 UTC, Maldaris commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
reee arbitrary nerfs

2021-02-06 04:32 UTC, coleminerman commented on whitesands/code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = {"A favorite among both the soldiers of the Space Russain Army and civillians out on the edges of explored space, the AK-47 is a reliable rifle designed and sold by a Space Russian company an
Yeah I was looking for something less cheesy, that's a good idea. I'll make the change.

2021-02-06 04:33 UTC, coleminerman commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
7 bullets to kill was a little much, the exact number for the change was suggested by someone else. Any suggestions for a better amount?

2021-02-06 04:34 UTC, coleminerman commented on whitesands/code/modules/projectiles/boxes_magazines/external/rifle.dm
> +	caliber = "5.45x39mm"
Why not, may as well. I'll add that in the same update as the description change.

2021-02-06 04:50 UTC, coleminerman commented
Update 1.1:
Made all changes suggested by @Maldaris.
This includes:
New ammo type more accurate to the IRL weapon
Changed description to make things sound less stupid and fix a spelling mistake that I've made hundreds of times and still haven't learned from

2021-02-06 04:50 UTC, coleminerman commented on whitesands/code/modules/projectiles/boxes_magazines/external/rifle.dm
> +	caliber = "5.45x39mm"
Fixed as of 1.1

2021-02-06 04:50 UTC, coleminerman commented on whitesands/code/modules/projectiles/guns/ballistic/automatic.dm
> +	desc = {"A favorite among both the soldiers of the Space Russain Army and civillians out on the edges of explored space, the AK-47 is a reliable rifle designed and sold by a Space Russian company an
Fixed as of 1.1

2021-02-06 04:52 UTC, Maldaris commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
It's supposed to be balanced around the fact they're a rare, high-difficulty mob on Whitesands. Since there's only a 1% drop chance from the mob, and only one guaranteed spawn on the map, it's a rare weapon, and I'd like to keep it balanced around that scarcity.

2021-02-06 04:53 UTC, coleminerman commented
Unforseen error causing crashes in version 1.1. Fixing now.

2021-02-06 05:08 UTC, WindowsErrors commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
balancing something by making it rare doesnt actually balance it

2021-02-06 05:11 UTC, coleminerman commented
Update 1.2:
Fixed a bunch of glitches caused by changing the ammo type in 1.1. Remind me to playtest every update next time before adding it to the PR.

2021-02-06 05:17 UTC, coleminerman commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
Don't worry, 1.1 fixed this. I gave the 47 its own ammo type, like requested, and then put the 74's ammo type back to where you had it originally. I was just wondering if you had any suggestions for changes to damage for the 47.

2021-02-06 05:18 UTC, Maldaris commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
I'd suggest asking in the discord for ideas.

2021-02-06 06:30 UTC, coleminerman commented on whitesands/code/modules/projectiles/projectile/bullets/rifle.dm
> -	damage = 32
Fixed as of 1.3

2021-02-06 06:32 UTC, coleminerman commented
Update 1.3:
Rebalanced the 74U and the 47 so that the 47 does more damage per shot but the 74U is still far more powerful due to other stat changes, which both makes sense due to ammo type and balancing for the fact that the 74U is a powerful bit of WhiteSands loot while the 47 is an addition to guncargo's arsenal.

2021-02-15 06:57 UTC, MarkSuckerberg approved these changes

2021-02-15 17:29 UTC, Maldaris approved these changes

2021-02-15 17:29 UTC, merged