1GlitchyCent's Security Rearming and also Many Unatomized Changes
Whitesands13/Whitesands pull request #756
Opened 2021-02-10 00:58 UTC by triplezeta

This PR would not be possible without @1glitchycent's beautiful sprites and @Jack7D1's immense efforts to get the energy shotgun working and to fix scatter laserguns.

**ALL NUMBERS IN THIS PR ARE SUBJECT TO CHANGE.** 

## About The Pull Request
#### ok lets get all of the stuff that isn't 100% tied to the actual major change out of the way first:
Derringer descriptions have had their grammar fixed
Ports https://github.com/tgstation/tgstation/pull/50637 and fixes scattershot energy weapons (such as the dragnet) not functioning (thank you Jack!)
Rubbershot 9mm ammunition has been added, and deals 20 stamina + 5 brute per shot.
Crackhead rifle and AK inhands have been moved out of the 64x guns icon files (why were they in there in the first place)
**Taser bolts have been nerfed to respect armor and deal only 40 stamina damage, and have a shorter range.**
**Scatter laser shotgun rounds deal 60 damage again.**

### Now for the actual changes:

Security officers now all start with a gun voucher in their backpacks instead of their hybrid taser. They can redeem this voucher at the sectech vendor for their choice of one of four weapons: 
![image](https://user-images.githubusercontent.com/51932018/107447979-f5eaad80-6afd-11eb-80f6-2ad72a66cfe3.png)

Starting from the top right and going clockwise:

***Hybrid Taser:*** The classic 2 phase stun gun. 20 disabler bolts that do 30 damage each, and 5 taser bolts with a shorter range that deals 40 stamina damage each.
***E-SG 255 Ultimate:*** It doesn't miss, and unlike the shitty hybrid taser it stops a criminal in their tracks in two hits. Fires a spread of 4 disabler bolts that do 15 damage each for a total of 60 damage, holding up to 5 shots. Comes with a built-in, fully functional NTOS tablet.
***E-TAR SMG:*** Do you feel like your alternatives are just a little... slow? Do you suck at aiming? Do you want to commit police brutality, but don't want to waste your precious commander ammo? Look no further, the E-TAR has you covered. Able to discharge 30 disabler bolts (that do 15 damage each) with an additional lethal mode that has 12 shots (that also do 15 damage each). With a firerate to match the SABR, this one's perfect for spray and pray combat.
***Vector SMG:*** its a 9mm smg thats loaded roundstart with rubbershot. thats it. 

TODO:
- [ ] add the armor voucher and armor variety too
- [ ] and make both vouchers able to be ordered, somehow
- [ ] make rubbershot 9mm printable once ballistic tech is researched
- [ ] and also make it come in ammo crates from cargo
- [ ] and have extra rubbershot purchasable from the sectech
- [ ] wouldnt it be funny if i added the ability to print incendiary and AP 9mm
- [ ] add new sounds so that shooting things feels better
- [ ] garotte wire? maybe? 👉👈 

## Why It's Good For The Game

## Changelog
:cl:
add: guns
add: rubbershot 9mm
tweak: scatter laser shotgun shells do 60 damage again
balance: taser shots do 40 stamina and respect armor
fix: scatter laser energy guns such as the dragnet function properly
spellcheck: derringer descriptions
/:cl:

2021-02-10 01:04 UTC, WindowsErrors commented
ooh, unatomized fixes and changes being put together, my favorite

2021-02-10 14:47 UTC, Vorak2 commented on code/modules/projectiles/boxes_magazines/external/smg.dm
> +	max_ammo = 20
this makes the Saber wierd as it has a 3 round burst so lowering the magazine capacity to 20 will lead to the last burst only having 2 shots.

2021-02-10 15:49 UTC, Shadowtail117 commented
> add: guns
> add: rubbershot 9mm

Please be more descriptive. E.g., "adds four new guns for security to choose from at roundstart"

2021-02-14 19:01 UTC, Maldaris requested changes

2021-02-14 19:01 UTC, Maldaris commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun_voucher //WS edit - gun gun gun gun gun gun gun
REEE nondescriptive meme comments.

2021-02-14 19:01 UTC, Maldaris commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun_voucher //WS edit - gun gun gun gun gun gun gun
REEE nondescriptive meme comments.

2021-02-15 17:34 UTC, triplezeta commented
fuck you stupid bot

2021-03-05 22:51 UTC, Superyodeler commented
Taking a look at this now.

2021-03-05 23:00 UTC, triplezeta commented
wait i thought i marked this as a draft

2021-03-05 23:25 UTC, Superyodeler commented
ae

2021-03-27 01:01 UTC, WindowsErrors commented
sad

2021-05-19 04:30 UTC, triplezeta commented
god damn fuck god damn thats a lot of commits holy shit

I'll pick this up again soon enough

2021-05-19 20:22 UTC, 1glitchycent commented
> god damn fuck god damn thats a lot of conflicts holy shit
> 
> I'll pick this up again soon enough

how

2021-05-21 00:24 UTC, Shadowtail117 commented
@triplezeta Is this PR ready for review or are you still working on it?

2021-05-21 01:07 UTC, untrius commented
I was told it's ready for review.

2021-05-21 17:41 UTC, Shadowtail117 requested changes
Preliminary review just for modularization and code cleanliness, I didn't test it yet.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	var/mob/living/shooter
Other than adding `pellet_delta` and `queued_delete`, this seems to be just shuffling around comments to be on their own lines. Any reason for this?

Also, add modularization comments.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +			to_chat(target, "<span class='userdanger'>You're hit by a [proj_name]!</span>")
```suggestion
			to_chat(target, "<span class='userdanger'>You're hit by \a [proj_name]\s!</span>")
```

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/ammunition/energy/stun.dm
> +	e_cost = 330
Please move to `whitesands/code/modules/projectiles/ammunition/energy/stun.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/boxes_magazines/external/smg.dm
> +	max_ammo = 20
Please take the above into account and consider reverting this change. If not, add a modularization comment.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/boxes_magazines/external/smg.dm
> +
Please move to `whitesands/code/modules/projectiles/boxes_magazines/external/smg.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/guns/ballistic/automatic.dm
> +	fire_rate = 4 //zedaedit: autorifle but awesome
Please make sure modularization comments are productive.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/guns/energy/laser.dm
> +	ammo_type = list(/obj/item/ammo_casing/energy/disabler/scatter, /obj/item/ammo_casing/energy/electrode)
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/projectile/beams.dm
> +	damage = 15
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/projectile/beams.dm
> +
Please move to `whitesands/code/modules/projectiles/projectile/beams.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +
Please move to `whitesands/code/modules/projectiles/bullets/pistol.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/projectile/energy/stun.dm
> +	range = 6
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/projectile/energy/stun.dm
> -		to_chat(target, "<span class='warning'>Your muscles seize, making you collapse[trait_check ? ", but your body quickly recovers..." : "!"]</span>")		//WS Edit End
Reasoning behind removing all of this?

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/research/designs/weapon_designs.dm
> +
Please move to `whitesands/code/modules/research/designs/weapon_designs.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/research/techweb/all_nodes.dm
> +	design_ids = list("mag_oldsmg", "mag_oldsmg_ap", "mag_oldsmg_ic", "commanderammo", "rubbershot9mm")
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/vending/security.dm
> +					/obj/item/ammo_box/c9mm/rubbershot = 3)
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/vending/security.dm
> +	var/items = list("E-TAR SMG", "Vector SMG", "E-SG 255", "Hybrid Taser")
The above comment seems to be better practice if you can make that change.

2021-05-21 17:41 UTC, Shadowtail117 commented on whitesands/code/modules/modular_computers/computers/item/internal.dm
> +	//It is critical that objects using this computer define the 'physical' var to ittself, otherwise the player won't be able to see the NTOS screen.
```suggestion
	//It is critical that objects using this computer define the 'physical' var to itself, otherwise the player won't be able to see the NTOS screen.
```

2021-05-21 17:41 UTC, Shadowtail117 commented on whitesands/code/modules/projectiles/guns/energy/laser.dm
> +	desc = "An energy shotgun with surveillance and statistics managing systems.\nApparently used to better inform command on how soldiers operate.\nRealistically used to compare kill counts and such."
Newlines in object descriptions are a bit suspect.
```suggestion
	desc = "An energy shotgun with surveillance and statistics managing systems. Apparently used to better inform command on how soldiers operate, realistically used to compare kill counts and such."
```

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	RegisterSignal(parent, COMSIG_PARENT_PREQDELETED, .proc/nullspace_parent)
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	UnregisterSignal(parent, list(COMSIG_PARENT_PREQDELETED, COMSIG_PELLET_CLOUD_INIT, COMSIG_GRENADE_PRIME, COMSIG_GRENADE_ARMED, COMSIG_MOVABLE_MOVED, COMSIG_MOVABLE_UNCROSSED, COMSIG_MINE_TRIGGERED,
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +			shell.newshot()
Modularization comment for these changes please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	num_pellets = all_the_turfs_were_gonna_lacerate.len + pellet_delta
Add modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		else if(!(body in bodies))
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		for(var/i in 1 to round(pellets_absorbed * 0.5))
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		RegisterSignal(target, COMSIG_PARENT_QDELETING, .proc/on_target_qdel, override=TRUE)
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		UnregisterSignal(target, COMSIG_PARENT_QDELETING)
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		qdel(parent)
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
>  	RegisterSignal(parent, COMSIG_MOVABLE_UNCROSSED, .proc/grenade_uncrossed)
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +
Please move to `whitesands/code/datums/components/pellet_cloud.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +		RegisterSignal(L, COMSIG_PARENT_QDELETING, .proc/on_target_qdel, override=TRUE)
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	purple_hearts -= target
Please move to `whitesands/code/datums/components/pellet_cloud.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun_voucher //WS edit - gun gun gun gun gun gun gun
Please keep modularization comments productive.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/gun_voucher //WS edit - gun gun gun gun gun gun gun
Please keep modularization comments productive.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/cargo/packs.dm
> +	desc = "Contains two 20-round magazines for the WT-550 Auto Rifle, three boxes of buckshot ammo, three boxes of rubber shotgun ammo, two boxes of rubbershot 9mm ammo, and one special .38 speedloader
Modularization comment please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/cargo/packs.dm
> +					/obj/item/ammo_box/c9mm/rubbershot,
Modularization comments please.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/jobs/job_types/security_officer.dm
> +	backpack_contents = list(/obj/item/melee/baton/loaded=1, /obj/item/ammo_box/magazine/co9mm=1, /obj/item/gun_voucher=1) //WS edit - free lethals //WS edit edit - pew
```suggestion
	backpack_contents = list(/obj/item/melee/baton/loaded=1, /obj/item/ammo_box/magazine/co9mm=1, /obj/item/gun_voucher=1) //WS edit - security rearming
```

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/ammunition/ballistic/pistol.dm
> +	projectile_type = /obj/projectile/bullet/c9mm/rubbershot
Please move to `/whitesands/code/modules/projectiles/ammunition/ballistic/pistol.dm`.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/ammunition/ballistic/shotgun.dm
> +	pellets = 4 //WS edit: makes scatter lasers based again
Please keep modularization comments productive.

2021-05-21 17:41 UTC, Shadowtail117 commented on code/modules/projectiles/ammunition/energy/laser.dm
> +
Please move to `whitesands/code/modules/projectiles/ammunition/energy/laser.dm`.

2021-05-23 05:31 UTC, triplezeta commented on code/datums/components/pellet_cloud.dm
> +	var/mob/living/shooter
on god do i need to add modularization comments if it's a port of a fix from TG

2021-05-23 05:33 UTC, Shadowtail117 commented on code/datums/components/pellet_cloud.dm
> +	var/mob/living/shooter
eee that makes more sense now. Nvm.

2021-09-11 22:07 UTC, closed without merging