ports nanoweave carpets from NSV
Whitesands13/Whitesands pull request #765
Opened 2021-02-14 10:54 UTC by triplezeta

## About The Pull Request

yo i probably should have asked for permission to do this beforehand but oh well

craft with plasteel

## Why It's Good For The Game

a less regal carpet to use for carpetty things

i should probably resprite these because they dont look that great up close now that i think of it

## Changelog
:cl:
add: nanoweave carpets
/:cl:

2021-02-15 06:41 UTC, MarkSuckerberg requested changes

2021-02-15 06:41 UTC, MarkSuckerberg commented on code/__DEFINES/icon_smoothing.dm
> +#define SMOOTH_GROUP_CARPET_NWBEIGE(75) //WS end
Move to modularized file

2021-04-24 04:35 UTC, untrius commented
Here's what they look like:

![image](https://user-images.githubusercontent.com/7697956/115947264-2e0e5500-a48c-11eb-8468-45aa99a402da.png)

2021-04-24 04:38 UTC, untrius commented
I didn't modularize the new smoothing group defines, because any change to them requires a change to the existing smoothing group file.

2021-05-03 13:56 UTC, untrius commented
I'm closing this for now.  But I want it on the record that it works, in case anyone ever decides to resprite these.

2021-05-03 13:56 UTC, closed without merging