Port sql query fixes
Whitesands13/Whitesands pull request #770
Opened 2021-02-15 06:32 UTC by Maldaris

## About The Pull Request

Ports https://github.com/tgstation/tgstation/pull/51564 , https://github.com/tgstation/tgstation/pull/52588 to fix some outstanding admin issues.

## Why It's Good For The Game

It'd be nice to manage bans again.

## Changelog
:cl:
fix: admeme panels fixed
/:cl:

2021-02-15 07:04 UTC, MarkSuckerberg requested changes

2021-02-15 16:52 UTC, dee-dubya commented
does this mean i won't have admin powers anymore

2021-02-23 05:16 UTC, Superyodeler approved these changes

2021-02-23 05:21 UTC, Superyodeler commented
Approved, Mald requested merge

2021-02-23 05:21 UTC, merged