Cool 96 Machine pistol
Whitesands13/Whitesands pull request #777
Opened 2021-02-18 03:32 UTC by 1glitchycent

gaming

## About The Pull Request

Adds the Cool 96 Machine pistol, an armor piercing option available to traitors for 12 TC. 25 damage, 2 shot burst, 30 AP(subject to change)
## Why It's Good For The Game

Adds a new option for traitor weaponry, meant to counter security.
## Changelog
:cl:
add: Cool 96 Machine pistol, magazines in available in uplink and Syndie ammo crate
imageadd: icons for the Mauser
/:cl:

2021-03-02 03:39 UTC, TheNeoGamer42 commented on whitesands/code/modules/cargo/packs.dm
> +	desc = "Contains three 10mm stechkin magazines, two .357 magnum speedloaders, two 8mm AP magazines, and a box of buckshot for good measure. Comes in a re-usable coffin."
bro you made a typo, I don't think your tec9 uses 8mm AP rounds

2021-03-02 03:40 UTC, triplezeta requested changes

2021-03-02 03:40 UTC, triplezeta commented on code/modules/projectiles/projectile/bullets/pistol.dm
> +	damage = 17
buffing this to 17 damage per shot seems really arbitrary. 👎

2021-03-02 03:40 UTC, triplezeta commented on whitesands/code/modules/cargo/packs.dm
> +	desc = "Contains three 10mm stechkin magazines, two .357 magnum speedloaders, two 8mm AP magazines, and a box of buckshot for good measure. Comes in a re-usable coffin."
9mm*

2021-03-16 17:14 UTC, Superyodeler approved these changes

2021-03-24 01:17 UTC, merged