Mahjong Tiles
Whitesands13/Whitesands pull request #808
Opened 2021-03-17 02:23 UTC by DanielJamesCox

## About The Pull Request

Adds a set of mahjong tiles to the game for playing riichi mahjong. A "wall" of tiles will act identically to a deck when used, and tiles will act similarly to cards, with the exception that ALL tiles in a "hand" will display.

## Why It's Good For The Game

Mahjong being in ss13 adds further depth to the amount of options you have for making a casino in the bar.

## Changelog
:cl:
add: Added a mahjong tile set and a wall to hold them
imageadd: Added 72 icons, 2 for each unique tile in Riichi Mahjong, and 1 for an assembled wall of tiles
/:cl:

2021-03-17 02:28 UTC, Epsilos commented
https://i.ytimg.com/vi/V07DHgZs-cI/hqdefault.jpg

2021-03-17 02:49 UTC, Shadowtail117 requested changes
Please modularize, i.e., put this in a new file in `/whitesands/code/game/objects/items/toys.dm`. Also note, not a thorough review, just brought up glaring issues.

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +			for(var/c = 0;c<3;c++)
Stylization, please add spaces for readability (`var/c = 0; c < 3; c++`).

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +//ATTACK HAND NOT CALLING PARENT
Comments seem redundant.

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +/obj/item/toy/mahjong/wall/proc/draw_card(mob/user)
Why not make the parameter `mob/living/user` to avoid needing the below cast? Do you expect slimes to be playing mahjong?

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +	var/obj/machinery/computer/holodeck/holo = null // Holodeck mahjong should not be infinite
Looking through this PR it doesn't seem like holo is set anywhere, only declared and then checked to see if it has any value. Are you planning on adding a mahjong set to the holodeck? If so I would look at how other holodeck programs keep track of virtual objects, since this seems very hacky.

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +	name = "a tile group"
```suggestion
	name = "tile group"
```
No pronouns in atom names. It's handled automatically by DM.

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +	desc = "A playing card used to play card games like poker."
```suggestion
	desc = "A tile used to play mahjong."
```

2021-03-17 02:49 UTC, Shadowtail117 commented on code/game/objects/items/toys.dm
> +	icon_state = "[cardname]"
Doesn't look like `cardname` is set anywhere, so when a new mahjong piece is created it will be set to `"[]"` = `""`. You can put something like:
```
var/list/tilenames = list(every, single, mahjong, tile, in, existence)
...
/obj/item/toy/mahjong/singletile/Initialize()
	. = ..()
	icon_state = "[pick(tilenames)]"

2021-03-17 03:09 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +	icon_state = "[cardname]"
Cardname is set when a tile is drawn from the deck, and the deck essentially just holds a list of strings to populate the tiles individually.

2021-03-17 03:10 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +	var/obj/machinery/computer/holodeck/holo = null // Holodeck mahjong should not be infinite
I was wondering about this too, and don't really plan to add them. I can simply remove this line if that sounds like the best course of action.

2021-03-17 03:36 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +			for(var/c = 0;c<3;c++)
They will now read "#-suit" and "red" and "mini" icons now have spaces

2021-03-17 03:59 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +/obj/item/toy/mahjong/wall/proc/draw_card(mob/user)
I don't want to speak for the person who originally wrote card code but generally it's good practice to separate specific functions (such as draw_card) from an input that might call them (such as attack_hand) on the off chance the code can be used elsewhere.

2021-03-17 05:28 UTC, Shadowtail117 reviewed
The file diff is showing `whitesands/icon/obj/toy.dmi` as an empty file, did you forget to copy over the sprites?

2021-03-17 18:42 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +	icon_state = "[cardname]"
Cardname is now set to haku by default just in case

2021-03-17 19:07 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +	desc = "A playing card used to play card games like poker."
Thanks for catching these two

2021-03-17 19:09 UTC, DanielJamesCox commented on code/game/objects/items/toys.dm
> +	var/obj/machinery/computer/holodeck/holo = null // Holodeck mahjong should not be infinite
As it turns out, this is stored here in order to make sure new tiles drawn are given a tag identical to their deck. As this works in card decks, I'm hesitant to remove it in case one does get put in the holodeck.

2021-03-23 03:24 UTC, Shadowtail117 submitted a review, later dismissed

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +	force = 0
This is already defined in:
https://github.com/Whitesands13/Whitesands/blob/13c67dc2609b2abe1bfbf5add15bc166cc1d2b17/code/game/objects/items/toys.dm#L28-L32
Not necessary to put it here too.

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +	user.visible_message("<span class='suicide'>[user] is trying to swallow \the [src]! It looks like [user.p_they()] [user.p_have()] a crummy hand!</span>")
If they're swallowing the tile, then you should probably delete the tile once it happens...unless you intend on them magically vomiting it back up postmortem.

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +			tiles += "[honor]"
The `[]` is not required as the list contains strings anyway. Just do:
```suggestion
			tiles += honor
```

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +	draw_card(user)
Bit iffy on ignoring calling the parent proc as that could potentially break something earlier down the line.

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +				to_chat(user, "<span class='warning'>The tiles are stuck to your hand, you can't add them to the deck!</span>")
```suggestion
				to_chat(user, "<span class='warning'>The tile is stuck to your hand, you can't add it to the deck!</span>")
```

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +			user.visible_message("<span class='notice'>[user] puts [user.p_their()] group of tiles in the wall.</span>", "<span class='notice'>You put the tiles in the wall.</span>")
Just consistency for the third vs. first person messages.
```suggestion
			user.visible_message("<span class='notice'>[user] puts [user.p_their()] group of tiles in the wall.</span>", "<span class='notice'>You put the group of tiles in the wall.</span>")
```

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +/obj/item/toy/mahjong
Generally best to put something like `abstract mahjong` for the name of this. It's not meant to be created in the world, so that lets someone know that there's an issue. Same for the description.

2021-03-23 03:24 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +	var/list/tiles = list()
It's possible that I'm not understanding this correctly (it's pretty complex code as-is), but `tiles` doesn't appear to actually be read from anywhere, only written. to. I also still don't see the connection between this and `/obj/item/toy/mahjong/singletile/Initialize()` - in your screenshot on the PR, did you manually spawn each tile or did you populate the set yourself? Alternatively, have you tested the full functionality of the mahjong set?

2021-03-23 03:27 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +	var/list/tiles = list()
Nevermind! I really am blind!
https://github.com/Whitesands13/Whitesands/blob/4a3eec4b183d9063d4234beedc63c2b5cf7df6e2/whitesands/code/game/objects/items/toys.dm#L68-L76
Now it makes sense. Ignore this comment.

2021-03-23 15:07 UTC, DanielJamesCox commented on whitesands/code/game/objects/items/toys.dm
> +/obj/item/toy/mahjong
Adding //Abstract to hold generic values for mahjong-related items

2021-03-24 08:30 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/toys.dm
> +/obj/item/toy/mahjong
Sorry, I meant in regards to the actual name of the item, in case it were spawned in the world by an unsuspecting admin. Something like:

```suggestion
/obj/item/toy/mahjong
	name = "concept of mahjong"
	desc = "An abstract concept of mahjong. If you're seeing this, something has gone horribly wrong and you should contact a coder."
```

2021-03-24 18:08 UTC, DanielJamesCox commented on whitesands/code/game/objects/items/toys.dm
> +	draw_card(user)
It appears to work on the original set of cards, and it does have specific functionality independent of picking the object up (which dragging to your sprite does), so I believe it's intentional. I don't want to fix what isn't broken if it could more readily lead to problems than leaving it.

2021-03-30 00:20 UTC, Superyodeler approved these changes
Seems to work

2021-04-06 00:57 UTC, SynnGraffkin commented
Unstales your PR @Superyodeler

2021-05-05 03:08 UTC, White-Sans commented
#### Test Merge Deployed

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 41d7189305b503ba153ebff4e8943a0222e9b10c
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: cb694876a0adfe9fb9b82cd7ac5be62b3f923ac0

2021-05-05 03:15 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 41d7189305b503ba153ebff4e8943a0222e9b10c
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: bb3f635ab0fb3cb83c1160218f2603841d27b0c2

2021-05-05 15:39 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: 4abac5722228bcc662ce18e550d0f8d4ded2fbe8

2021-05-11 23:04 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: abfa3735de453c4b57d660b6395b8dd093357c00

2021-05-12 22:06 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: 8aaf1d92960aed79a6613351246470472346413c

2021-05-14 06:25 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

2021-05-14 15:12 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

2021-05-16 18:37 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

2021-05-16 19:20 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

2021-05-16 19:33 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: f5a8346aa55c5189179a681ae74114fe54382bba
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: f9cf10d540a86e94bbf65b05344ba407ccc97d0d

2021-05-18 02:10 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: c8b752239aef9ffc4e68d7bc7bbef816f462533c
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: d46bea6a85d7a8fca138151a32be363fa4ff9eb9

2021-05-18 02:31 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: d0b00f8425ceac646b6ce473bc1494c9ebd37b02
Pull Request: 2494337b31a4352a07f0d0eb5e4b78006e26026c
Server: 0899231c74c388b98b965aac407f7ad233a1aa1f

2021-05-18 03:10 UTC, merged

2021-05-18 03:18 UTC, White-Sans commented
#### Test Merge Removed