White Sands Basilisk Update
Whitesands13/Whitesands pull request #821
Opened 2021-03-24 18:21 UTC by TheRealScarHomie

## About The Pull Request

Retextures the Basilisk on the white sands planet with amazing sprites made in the bounty from INFRARED_BARON, also mixes up how they work a bit, actually makes the freeze blast they shoot slow you and also adds in shells on them that you have to crack before you start doing damage.

![image](https://user-images.githubusercontent.com/63623569/112363750-c074da80-8ccd-11eb-88f5-a6f867e470d1.png)

## Changelog
:cl:
add: Added new basilisk sprite and type
balance: Changes new basilisks to be the dominant critter on white sands
/:cl:

2021-03-24 20:06 UTC, SynnGraffkin commented
👀

2021-03-24 20:08 UTC, Jack7D1 commented
ahem, pog

2021-04-01 00:42 UTC, Superyodeler commented
Will check this out

2021-04-01 22:58 UTC, Superyodeler requested changes
There's a bunch of leftover stuff from how the watcher's currently work that's been left in, also some duplicates.

2021-04-01 22:58 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +	armor = list("melee" = 50, "bullet" = 50, "laser" = 100, "energy" = 100, "bomb" = 30, "bio" = 30, "rad" = 30, "fire" = 30, "acid" = 30)
```suggestion
```
With these changes the watcher is meant to be invulnerable until the armor is broken, so it doesn't need armor values at all.

2021-04-01 22:58 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
>  	if(has_shell)
```suggestion
```
shell_damage handles this further down.

2021-04-01 22:58 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
>  			armor = null		// Armor comes from the shell
```suggestion
```
shell_damage handles this further down.

2021-04-01 22:58 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +				armor = null		// Armor comes from the shell
```suggestion
```
With the way the mob would work with these changes there's no need for armor.

2021-04-01 22:59 UTC, Superyodeler commented
The sprites are good, but I'm not sure I like the idea of changing the armor from what it is now to just a second health pool.

2021-04-01 23:34 UTC, Superyodeler requested changes
Update to my previous review, if you stick with the extra health shell method it would probably be better to just increase the mob's hp by 120 and make the damage procs change the icon state.

2021-04-06 01:06 UTC, TheRealScarHomie commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +	armor = list("melee" = 50, "bullet" = 50, "laser" = 100, "energy" = 100, "bomb" = 30, "bio" = 30, "rad" = 30, "fire" = 30, "acid" = 30)
the armor takes damage away from the second shell, saves giving it a ton of health

2021-04-06 12:58 UTC, TheRealScarHomie commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +				armor = null		// Armor comes from the shell
the armor would be removed when the shell is, allowing for full damage

2021-04-06 17:58 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +				armor = null		// Armor comes from the shell
Armor doesn't effect damage dealt to the shell.

2021-04-06 21:36 UTC, TheRealScarHomie commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +				armor = null		// Armor comes from the shell
are you sure? it acts like it does

2021-04-07 20:35 UTC, TheRealScarHomie commented
Alright changed how it works to just call everything on health based on the Life() proc, damaging calls the proc so it all happens in real time aswell, works the same in a whole lot less code.

2021-04-07 23:36 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +	Life()
Is there a reason you're calling life here? Life gets called every tick.

2021-04-08 01:50 UTC, TheRealScarHomie commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +	Life()
so damaging it updates it, ticks arent very fast, it seems awkward when its damaged and dosent update till it moves

2021-04-16 00:36 UTC, Superyodeler commented
Been busy, will look at this some more

2021-04-20 22:10 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +					looted = TRUE
Should probably move this into it's own function that can be called when the basilisk is attacked rather than calling life().

2021-04-20 23:06 UTC, TheRealScarHomie commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +					looted = TRUE
then it would be in life() and another proc then, this is more efficient

2021-04-20 23:48 UTC, Superyodeler commented on whitesands/code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
> +					looted = TRUE
You can call the function both in life and in the attacked procs, calling all of life just to use a bit of code at the end of it is not efficient

2021-05-05 03:15 UTC, White-Sans commented
#### Test Merge Deployed

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 41d7189305b503ba153ebff4e8943a0222e9b10c
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: bb3f635ab0fb3cb83c1160218f2603841d27b0c2

2021-05-05 15:39 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 4abac5722228bcc662ce18e550d0f8d4ded2fbe8

2021-05-11 23:04 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: abfa3735de453c4b57d660b6395b8dd093357c00

2021-05-12 22:06 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 8aaf1d92960aed79a6613351246470472346413c

2021-05-14 06:25 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

2021-05-14 15:12 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

2021-05-16 18:37 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

2021-05-16 19:20 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

2021-05-16 19:33 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: f5a8346aa55c5189179a681ae74114fe54382bba
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: f9cf10d540a86e94bbf65b05344ba407ccc97d0d

2021-05-18 02:10 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: c8b752239aef9ffc4e68d7bc7bbef816f462533c
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: d46bea6a85d7a8fca138151a32be363fa4ff9eb9

2021-05-18 02:31 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: d0b00f8425ceac646b6ce473bc1494c9ebd37b02
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 0899231c74c388b98b965aac407f7ad233a1aa1f

2021-05-18 03:18 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: eb861ce0b96e035393d6ce959b95704858b23f53
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 07a57557a3177bf81d4578a7d2929764d5ce6483

2021-05-18 03:41 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 7b932bce04fb2a7fda877ae1df3f3d876eeea5ee

2021-05-18 16:09 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: dbac6e9bf5ed9d7defe9e0da1eadb359cd9ac642

2021-05-18 22:42 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: bd4cf2415f05b72bcae48f8f27808b66ee8a3d66
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: d6cfadd2b01f764a6e2209569802957819946c4c

2021-05-18 23:27 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 24f4f50761fbf5b45efa8d5e851cb8fbd68390f7
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: 5ccb5e929be08b6549769869a4ddc69723be8ff5

2021-05-19 01:01 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8f310c08e62df2a7ffbed5e57a2721f521ce8723
Pull Request: 424e94730f1da748f366e78460a2c0010877a137
Server: a4ae8d2f045b0245293ed1d64c64b04f82e07962

2021-06-01 16:28 UTC, Superyodeler approved these changes

2021-06-01 22:56 UTC, merged