Cigarette Overhaul
Whitesands13/Whitesands pull request #824
Opened 2021-03-29 17:28 UTC by TheRealScarHomie

## About The Pull Request

Completely Overhauls the Cigarettes and Cigars Functionally and Visually, Now you don't die immediately after smoking like 3 cigarettes, the scale has changed it so after 2 you gradually rise up taking damage, while not smoking reduces the damage of 1 cigarette a minute, more so to penalize chain smokers rather than boof you for having a smoke every now and then. New cigarette types and sprites, overhauls to visuals all round to better suit our style.

## New Types

- nanotransen smokes
- donkco smokes
- waffleco smokes
- solgov smokes
- superfresh smokes
- turbo smokes
- syndicate smokes

- cigar
- robusto
- robusto gold

all of them do different stuff so experiment and find out! (or read the code)

disclaimer: havanas', normal rollies and most other things that lie outside of smokeables are the same still (just resprited)

## Images

![image](https://user-images.githubusercontent.com/63623569/112874014-491ebc80-90ba-11eb-9b62-3d8cb7977282.png)

![image](https://user-images.githubusercontent.com/63623569/112874111-6bb0d580-90ba-11eb-92b9-2721dc547ef4.png)

## Changelog
:cl:
add: Added new Cigarette/Cigar/Rollie Sprites and Types
add: Complete overhaul of how shit works (sorta)
add: Gradual smoking icons
balance: Fixes lung damage when smoking, now gradual and punishes chain smoking
tweak: Slight derringer change (cigar box now, very classy)
delete: my soul, old code has left its mark, I am left to wander the abyss
/:cl:

2021-03-29 17:30 UTC, TheRealScarHomie commented
also some mainta' who can actually code shit to be better needs to look at this with a fine comb, there a probably way better ways of doing shit, most old code remains unboofed, just butchered

2021-03-29 18:12 UTC, AsciiSquid requested changes
In addition I'd suggest giving a cig brand mindbreaker again for the sake of those who run the mental instability quirk.

2021-03-29 18:12 UTC, AsciiSquid commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +	STR.set_holdable(list(/obj/item/clothing/mask/cigarette, /obj/item/lighter))
```suggestion
	STR.set_holdable(list(/obj/item/clothing/mask/cigarette, /obj/item/lighter, /obj/item/match))
```

2021-03-29 18:12 UTC, AsciiSquid commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +	list_reagents = list(/datum/reagent/drug/nicotine = 10, get_random_reagent_id() = rand(5,20))
I fully endorse the potential chaos

2021-03-29 20:40 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/storage/fancy.dm
> +	name = "Robusto cigar case"
what does the /improper even do? arent they a relic of pre-pronoun code?

2021-03-29 20:42 UTC, Shadowtail117 commented on whitesands/code/game/objects/items/storage/fancy.dm
> +	name = "Robusto cigar case"
It controls whether or not BYOND will automatically add a "the" before the name. By default, anything that's capitalized is treated as a proper noun, and you have to specify if it's otherwise. If you don't then you'll have something like "You take a cigar out of Robusto cigar case" instead of "You take a cigar out of the Robusto cigar case".

2021-03-30 21:15 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +	STR.set_holdable(list(/obj/item/clothing/mask/cigarette, /obj/item/lighter))
done

2021-03-30 21:15 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/storage/fancy.dm
> +	name = "Robusto cigar case"
done

2021-03-30 21:15 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/storage/fancy.dm
> +			if(!(istype(C, /obj/item/gun/ballistic/derringer/gold) || istype(C, /obj/item/gun/ballistic/derringer/traitor)) && istype(C, /obj/item/gun/ballistic/derringer))
done

2021-03-30 21:15 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/storage/fancy.dm
> +			if(!(istype(C, /obj/item/gun/ballistic/derringer/gold) || istype(C, /obj/item/gun/ballistic/derringer/traitor)) && istype(C, /obj/item/gun/ballistic/derringer))
and tested 😳

2021-03-30 21:17 UTC, TheRealScarHomie commented on whitesands/code/modules/uplink/uplink_items.dm
>  	desc = "An easily concealable handgun capable of firing .357 rounds. Comes in an inconspicuious packet of cigarettes with additional munitions."
done

2021-03-31 01:32 UTC, TheRealScarHomie commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +	list_reagents = list(/datum/reagent/drug/nicotine = 10, get_random_reagent_id() = rand(5,20))
goddamn straight

2021-03-31 21:48 UTC, AsciiSquid commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +	STR.set_holdable(list(/obj/item/clothing/mask/cigarette, /obj/item/lighter, /obj/item/reagent_containers/food/snacks/donkpocket))
```suggestion
	STR.set_holdable(list(/obj/item/clothing/mask/cigarette, /obj/item/lighter, /obj/item/match, /obj/item/reagent_containers/food/snacks/donkpocket))
```

2021-03-31 21:48 UTC, AsciiSquid commented on whitesands/code/game/objects/items/cigs_cigars.dm
> +/obj/item/storage/fancy/cigarettes/ComponentInitialize()
Duplicate declaration at line 26

2021-03-31 21:48 UTC, AsciiSquid commented on whitesands/code/modules/uplink/uplink_items.dm
> +	desc = "An easily concealable handgun capable of firing .357 rounds. Comes in an inconspicuous box of cigars with additional munitions.."
```suggestion
	desc = "An easily concealable handgun capable of firing .357 rounds. Comes in an inconspicuous box of cigars with additional munitions."
```
Extra period

2021-04-06 01:05 UTC, TheRealScarHomie commented
okay all good

2021-04-15 14:08 UTC, AsciiSquid approved these changes

2021-04-15 20:08 UTC, WindowsErrors commented
you ever try cigarettes yet
![Screenshot_1400](https://user-images.githubusercontent.com/58999300/114931821-9786c780-9deb-11eb-9531-d7aee0af7a0d.png)

2021-05-05 03:15 UTC, White-Sans commented
#### Test Merge Deployed

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 41d7189305b503ba153ebff4e8943a0222e9b10c
Pull Request: a353023aeccc9146fd15404adb485ccff4978957
Server: bb3f635ab0fb3cb83c1160218f2603841d27b0c2

2021-05-05 05:03 UTC, WindowsErrors commented
it's been five weeks

2021-05-05 05:39 UTC, lunaboards-dev commented
> it's been five weeks

yeah, we just got test merges working

2021-05-05 15:39 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: a353023aeccc9146fd15404adb485ccff4978957
Server: 4abac5722228bcc662ce18e550d0f8d4ded2fbe8

2021-05-11 23:04 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: cbd9781d5c663de5d882eb39d9ee5a93006deb02
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: abfa3735de453c4b57d660b6395b8dd093357c00

2021-05-12 22:06 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: e8c6725e5975e248cc015d29b3bf53b02312ce87
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 8aaf1d92960aed79a6613351246470472346413c

2021-05-14 06:25 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: e29ee0a0e1b68cab4f437b8af05286a0b7209311

2021-05-14 15:12 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 4249193b5915ffce64976f84733b4fc897020a8e
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 0c46f0c046c353b003e0df0f8b5d106cd6eccd8b

2021-05-16 18:37 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: ca7dbd1078291f30df3fe4805de872df072db0e5
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: c789e6bb6f48e280805fe0f959f82559ca79a961

2021-05-16 19:20 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: dacdc2ee84d84719e0e8badfaa6c6752d5f8ec7d
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 35b901f541c3c909a94b8338c5c423bd7c038ece

2021-05-16 19:33 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: f5a8346aa55c5189179a681ae74114fe54382bba
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: f9cf10d540a86e94bbf65b05344ba407ccc97d0d

2021-05-18 02:10 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: c8b752239aef9ffc4e68d7bc7bbef816f462533c
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: d46bea6a85d7a8fca138151a32be363fa4ff9eb9

2021-05-18 02:31 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: d0b00f8425ceac646b6ce473bc1494c9ebd37b02
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 0899231c74c388b98b965aac407f7ad233a1aa1f

2021-05-18 03:18 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: eb861ce0b96e035393d6ce959b95704858b23f53
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 07a57557a3177bf81d4578a7d2929764d5ce6483

2021-05-18 03:41 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 7b932bce04fb2a7fda877ae1df3f3d876eeea5ee

2021-05-18 16:09 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8a9cbd8b817f506cb23cd836ac59a72af74f1787
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: dbac6e9bf5ed9d7defe9e0da1eadb359cd9ac642

2021-05-18 22:42 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: bd4cf2415f05b72bcae48f8f27808b66ee8a3d66
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: d6cfadd2b01f764a6e2209569802957819946c4c

2021-05-18 23:27 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 24f4f50761fbf5b45efa8d5e851cb8fbd68390f7
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: 5ccb5e929be08b6549769869a4ddc69723be8ff5

2021-05-19 01:01 UTC, White-Sans commented
#### Test Merge Updated

##### Server Instance
White Sands

##### Merged By
Admin

##### Revision
Origin: 8f310c08e62df2a7ffbed5e57a2721f521ce8723
Pull Request: 9feb92371e17e818513894114f84c5ea301994ef
Server: a4ae8d2f045b0245293ed1d64c64b04f82e07962

2021-05-24 01:20 UTC, untrius approved these changes

2021-06-17 00:25 UTC, merged